Instance: "kingspeak"

# Site information that should match the CE Topology registration
Site:
  Resource: SLATE_US_UUTAH_KINGSPEAK
  ResourceGroup: CHPC Group
  Sponsor: osg:100
  Contact: Mitchell Steinman
  ContactEmail: chpc-osg-support@lists.utah.edu
  City: Salt Lake City
  Country: United States
  Latitude: 40.7608
  Longitude: -111.891

Cluster:
  RemoteHost: kingspeak1.chpc.utah.edu
  RemoteBatch: slurm
  PrivateKeySecret: utah-kp-hostedce-privkey # maps to SLATE secret
  Memory: 8192
  CoresPerNode: 4
  MaxWallTime: 4320
  AllowedVOs: osg, cms, atlas, glow, hcc, fermilab, ligo, virgo, sdcc, sphenix, gluex, icecube, xenon

Storage:
  GridDir: /uufs/chpc.utah.edu/common/home/osguserk/bosco-osg-wn-client
  WorkerNodeTemp: /scratch/local/.osgscratch

Squid:
  Location: sl-uu-es1.slateci.io:31726
  
Networking:
  # The hostname that the CE should use. 
  # Appropriate A and PTR DNS records must exist.
  Hostname: "sl-uu-hce1.slateci.io"
  # The preferred IP address which should be requested from the LoadBalancer. 
  # This may be left as null to express no preference. 
  # Setting this may be useful when redeploying a CE in order to try to get
  # back the same IP address that was used previously. 
  RequestIP: 155.101.6.240

########### REQUIRED ###########
# Specify additional HTCondor-CE configuration. JOB_ROUTER_ENTRIES is required!
HTCondorCeConfig: |+
  JOB_ROUTER_ENTRIES @=jre
  [
    GridResource = "batch slurm osguserk@kingspeak1.chpc.utah.edu";
    Requirements = (Owner == "osguserk");
    set_default_queue = "kingspeak-osg";
    # 16 GB
    set_default_maxMemory = 8192;
    # 72 hours
    set_BatchRuntime = 259200;
    # 4 core jobs
    set_default_xcount = 4;
  ]
  @jre
# Options to allow override of the bosco directory from arbitrary git repos
# Bosco override dirs are expected in the following location in the git repo:
#   <RESOURCE NAME>/bosco_override/
BoscoOverrides:
  Enabled: true
  GitEndpoint: "https://github.com/slateci/utah-bosco.git"
  RepoNeedsPrivKey: false
  GitKeySecret: none

# Enable a logging sidecar
HTTPLogger:
  Enabled: true
  # If you want to insert a password instead of using a randomly generated one,
  # point Secret to a K8S/SLATE secret below.
  # Secret: my-secret

# Default VO-user mappings for OSG Hosted CEs
# Change these contents for legacy OSG Hosted CEs or non-OSG Hosted CEs
VomsmapOverride: |+
  "/osg/Role=NULL/Capability=NULL" osguserk
  "/GLOW/Role=htpc/Capability=NULL" osguserk
  "/hcc/Role=NULL/Capability=NULL" osguserk
  "/cms/*" osguserk
  "/fermilab/*" osguserk
  "/osg/ligo/Role=NULL/Capability=NULL" osguserk
  "/virgo/ligo/Role=NULL/Capability=NULL" osguserk
  "/sdcc/Role=NULL/Capability=NULL" osguserk
  "/sphenix/Role=NULL/Capability=NULL" osguserk
  "/atlas/*" osguserk
  "/Gluex/Role=NULL/Capability=NULL" osguserk
  "/dune/Role=pilot/Capability=NULL" osguserk
  "/icecube/Role=pilot/Capability=NULL" osguserk
  "/xenon.biggrid.nl/Role=NULL/Capability=NULL" osguserk

# If you wish to allow yourself to submit to this CE with your personal grid
# proxy, you can put that in below. This will get directly mapped into
# /etc/grid-security/grid-mapfile
#
GridmapOverride: |+
  "/DC=org/DC=cilogon/C=US/O=University of Utah/CN=HENRY STEINMAN A14364946" osguserk

# Use a pre-existing certificate/key pair stored in a secret with
# # 'hostcert.pem' and 'hostkey.pem' keys for the host certificate and
# # key, respectively
Certificate:
  Secret: null

# FOR DEVELOPMENT PURPOSES ONLY!
# Setting 'Enabled: true' below does the following:
# - Configures the CE as an ITB host
# - Generates a test CA and self-signed host cert/key pair
Developer:
  Enabled: false

