Instance: "notchpeak"

# Site information that should match the CE Topology registration
Topology:
  Resource: SLATE_US_UUTAH_NOTCHPEAK
  Sponsor: osg:100
  Contact: Mitchell Steinman
  ContactEmail: chpc-osg-support@lists.utah.edu
  City: Salt Lake City
  Country: United States
  Latitude: 40.7608
  Longitude: -111.891

RemoteCluster:
  LoginHost: notchpeak1.chpc.utah.edu
  Batch: slurm
  PrivateKeySecret: utah-np-hostedce-privkey # maps to SLATE secret
  MemoryPerNode: 24576
  CoresPerNode: 4
  MaxWallTime: 4320
  GridDir: /uufs/chpc.utah.edu/common/home/osgusern/bosco-osg-wn-client
  WorkerNodeTemp: /scratch/local/.osgscratch
  Squid: sl-uu-es1.slateci.io:31726
  
Networking:
  ServiceType: "LoadBalancer"
  # The hostname that the CE should use. 
  # Appropriate A and PTR DNS records must exist.
  Hostname: "sl-uu-hce3.slateci.io"
  # The preferred IP address which should be requested from the LoadBalancer. 
  # This may be left as null to express no preference. 
  # Setting this may be useful when redeploying a CE in order to try to get
  # back the same IP address that was used previously. 
  RequestIP: 155.101.6.236

# Specify additional HTCondor-CE configuration
HTCondorCeConfig: |+
  JOB_ROUTER_ENTRIES @=jre
  [
    Name = "Notchpeak_default";
    set_default_queue = "notchpeak-osg";
    # 16 GB
    set_default_maxMemory = 16384;
    # 72 hours
    set_BatchRuntime = 259200;
    # 8 core jobs 
    set_default_xcount = 8;
  ]
  @jre

  JOB_ROUTER_ROUTE_NAMES = Notchpeak_default

# Options to allow override of the bosco directory from arbitrary git repos
# Bosco override dirs are expected in the following location in the git repo:
#   <RESOURCE NAME>/bosco_override/
BoscoOverrides:
  Enabled: true
  GitEndpoint: "https://github.com/slateci/utah-bosco.git"
  GitKeySecret: null

# Enable a logging sidecar
HTTPLogger:
  Enabled: true
  # If you want to insert a password instead of using a randomly generated one,
  # point Secret to a K8S/SLATE secret below.
  # Secret: my-secret

# Default VO-user mappings for OSG Hosted CEs
# Change these contents for legacy OSG Hosted CEs or non-OSG Hosted CEs
VoRemoteUserMapping:
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/OSG.yaml
  - "/osg/Role=NULL/Capability=NULL": osgusern
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/GLOW.yaml
  - "/GLOW/Role=htpc/Capability=NULL": osgusern
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/HCC.yaml
  - "/hcc/Role=NULL/Capability=NULL": osgusern
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/CMS.yaml
  - "/cms/*": osgusern
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/Fermilab.yaml
  - "/fermilab/*": osgusern
  # osg06 reserved for JLAB
  # LIGO-Virgo collaboration
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/LIGO.yaml
  - "/osg/ligo/Role=NULL/Capability=NULL": osgusern
  - "/virgo/ligo/Role=NULL/Capability=NULL": osgusern
  # Brookhaven National Lab VOs
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/sPHENIX.yaml
  - "/sdcc/Role=NULL/Capability=NULL": osgusern
  - "/sphenix/Role=NULL/Capability=NULL": osgusern
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/ATLAS.yaml
  - "/atlas/*": osgusern
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/Gluex.yaml
  - "/Gluex/Role=NULL/Capability=NULL": osgusern
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/DUNE.yaml
  - "/dune/Role=pilot/Capability=NULL": osgusern
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/IceCube.yaml
  - "/icecube/Role=pilot/Capability=NULL": osgusern
  # https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/XENON.yaml
  - "/xenon.biggrid.nl/Role=NULL/Capability=NULL": osgusern


# If you wish to allow yourself to submit to this CE with your personal grid
# proxy, you can put that in below. This will get directly mapped into
# /etc/grid-security/grid-mapfile
#
DnRemoteUserMapping:
  - "/DC=org/DC=cilogon/C=US/O=University of Utah/CN=HENRY STEINMAN A14364946": osgusern

HostCredentials:
  # Use a pre-existing host key to request a new Let's Encrypt
  # certificate If HostCertSecret is also specified, the Let's Encrypt
  # request is skipped.  Secret must contain a "host.key" key
  # containing the encoded host key.
  HostKeySecret: null
  # Use a pre-existing host certificate instead of requesting a new
  # Let'S Encrypt certificate. If HostKeySecret is not specified, a
  # new Let's Encrypt certificate and key are requested anyway.
  # Secret must contain a "host.cert" containing the encoded host
  # certificate.
  HostCertSecret: null

# FOR DEVELOPMENT PURPOSES ONLY!
# Setting 'Enabled: true' below does the following:
# - Configures the CE as an ITB host
# - Generates a test CA and self-signed host cert/key pair
Developer:
  Enabled: null

